name: "deploy terraform"
description: "Performs a deploy with terraform"
inputs:
  BACKEND_BUCKET_NAME:
    required: true
    description: "The bucket name to store the state"
  BACKEND_STATE_KEY:
    required: true
    description: "The state key in which the state is stored"
  WORKING_DIRECTORY:
    required: true
    description: "The working directory"
  TERRAFORM_ADDITIONAL:
    required: false
    default: ""
    description: "Additional terraform commands to pass to build"
  TERRAFORM_WRAPPER:
    required: false
    default: true
    description: "If the terraform output should be wrapped"
runs:
  using: "composite"
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: ${{ inputs.TERRAFORM_WRAPPER }}

    - name: Terraform Init
      working-directory: ${{ inputs.WORKING_DIRECTORY }}
      run: terraform init
      shell: bash

    - name: Terraform Apply
      working-directory: ${{ inputs.WORKING_DIRECTORY }}
      run: terraform apply -auto-approve -input=false ${{ inputs.TERRAFORM_ADDITIONAL }}
      shell: bash
