name: Deployment

on:
  workflow_run:
    workflows: [ "Checks" ]
    types:
      - completed

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
  ARM_ACCESS_KEY: ${ secrets.AZURE_TERRAFORM_ACCESS_KEY }

jobs:
  build:
    name: Build, push, and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@master

      - name: Deploy Terraform
        uses: ./.github/actions/deploy-terraform
        with:
          BACKEND_STATE_KEY: "terraform.tfstate"
          BACKEND_BUCKET_NAME: "rejdeboer"
          WORKING_DIRECTORY: ./deployment

      - name: Build container image
        run: docker build -t emailapi.azurecr.io/repo:email-api .

      - name: Push image to Docker Hub
        run: docker push emailapi.azurecr.io/repo:email-api
